# Generated by Django 4.2.6 on 2023-11-06 00:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "first_commit",
                    models.DateTimeField(
                        help_text="Datetime of first commit", null=True
                    ),
                ),
                (
                    "latest_commit",
                    models.DateTimeField(
                        help_text="Datetime of latest commit", null=True
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[("quark", "Quark"), ("extension", "Extension")],
                        max_length=64,
                    ),
                ),
                (
                    "git_url",
                    models.URLField(
                        max_length=1024,
                        unique=True,
                        verbose_name="URL of git repository",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("project_help", models.TextField()),
                (
                    "project_help_formatting",
                    models.CharField(
                        choices=[("rst", "RST"), ("md", "Markdown"), ("raw", "Raw")],
                        help_text="Used formatting for text file",
                        max_length=40,
                    ),
                ),
                (
                    "quark_info",
                    models.JSONField(
                        default=dict, help_text="Extracted info from quark file"
                    ),
                ),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True, related_name="dependents", to="quarks.project"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("version_name", models.CharField(max_length=1024)),
                (
                    "release_date",
                    models.DateTimeField(help_text="Derived from git push"),
                ),
                (
                    "git_hash",
                    models.CharField(
                        help_text="Hash of associated git commit",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Potential URL to release", null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="quarks.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "-release_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDoc",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("html_file", models.FileField(upload_to="sc_docs")),
                (
                    "source_path",
                    models.CharField(
                        help_text="Source code path of help file in repository",
                        max_length=512,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="quarks.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "source_path"],
            },
        ),
        migrations.CreateModel(
            name="ProjectClass",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path of file which declares the class",
                        max_length=400,
                    ),
                ),
                ("name", models.CharField(help_text="Name of class", max_length=400)),
                (
                    "super_class",
                    models.CharField(
                        blank=True,
                        help_text="Optional super class",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "is_extension",
                    models.BooleanField(default=False, help_text="Is class extension"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="quarks.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "is_extension", "name"],
            },
        ),
    ]
