# Generated by Django 4.2.7 on 2023-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_branch",
            field=models.CharField(default="master", max_length=200),
        ),
    ]
