name: mypy

permissions:
    contents: read
    checks: write
    id-token: write

on:
    pull_request:
    push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'pip'
        - run: pip install -r requirements.txt
        - run: mypy .
          working-directory: ./baryon
        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure()
          with:
            report_paths: './baryon/.mypy.xml'
