name: test_scraping_run

on:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test_scraping_run
    steps:
        - uses: actions/checkout@v3
        - name: Cache Docker images.
          uses: ScribeMD/docker-cache@0.3.6
          with:
            key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
        - run: docker build -t baryon .
        - run: docker run --env DJANGO_SETTINGS_MODULE=baryon.settings.dev baryon /bin/bash -c "python manage.py migrate && python manage.py scrape_quarks"
